#services:
#  backend:
#    build: app
#    container_name: bitrix-app
#    ports:
#      - "3000:3000"
#    depends_on:
#      - postgres
#      - redis
#    env_file:
#      - .env
#    restart: unless-stopped
#
#  postgres:
#    image: postgres:latest
#    container_name: nest-chat_database
#    ports:
#      - "3001:5432"
#    env_file:
#      - .env
#      - user-service/.env
#    volumes:
#      - /home/data/nest-docker/pgdata:/var/lib/postgresql/data
#    restart: unless-stopped
#
#  redis:
#    image: redis:latest
#    container_name: nest-chat_redis
#    ports:
#      - "3002:6379"
#    volumes:
#      - /home/data/nest-docker/redisdata:/data
#    command: [ "redis-server", "--appendonly", "yes" ]
#
#volumes:
#  pgdata:
#    driver: local
