services:
  # Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bitrix-server-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    volumes:
      - /home/data/bitrix24/logs/debug:/app/logs
    networks:
      - monitoring
    restart: always

  postgres:
    image: postgres:latest
    container_name: bitrix-server-postgres
    ports:
      - "3005:5432"
    env_file:
      - ./.env
    volumes:
      - /home/data/bitrix24/database/postgres:/var/lib/postgresql/data
    networks:
      - monitoring

  # Redis
  redis:
    image: redis:latest
    container_name: bitrix-server-redis
    env_file:
      - ./.env
    ports:
      - "3001:6379"
    volumes:
      - /home/data/bitrix24/redisdata:/data
    networks:
      - monitoring
    command: redis-server --requirepass  ${REDIS_PASSWORD}
    restart: always

  # Storage logs
  loki:
    image: grafana/loki:latest
    container_name: bitrix-server-grafana_loki
    ports:
      - "3002:3100"
    volumes:
      - loki_data:/loki
    networks:
      - monitoring
    command: -config.file=/etc/loki/local-config.yaml
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -tries=1 -O- http://localhost:3100/ready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: bitrix-server-prometheus
    ports:
      - "3003:9090"
    volumes:
      - ./config/prometheus:/etc/prometheus-config
      - prometheus_data:/prometheus
    networks:
      - monitoring
    command:
      - --config.file=/etc/prometheus-config/prometheus.yaml
    restart: on-failure
    depends_on:
      - backend

  # Dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: bitrix-server-grafana
    ports:
      - "3004:3000"
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana:/etc/grafana-config
      - ./config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - monitoring
    depends_on:
      - prometheus
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --tries=1 -O- http://localhost:3000/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Collection lgos
  promtail:
    image: grafana/promtail:latest
    container_name: bitrix-server-promtail
    volumes:
      - /home/data/bitrix24/logs/debug:/app/logs:ro # logging backend files
      - /var/run/docker.sock:/var/run/docker.sock # logging backend console
      - ./config/promtail/promtail.yml:/etc/promtail/config.yml
      - /home/data/bitrix24/promtail-positions:/tmp
      - /var/log:/var/log:ro # logging other logs. Ex: nginx
    networks:
      - monitoring
    command: -config.file=/etc/promtail/config.yml

networks:
  monitoring:
    driver: bridge

volumes:
  loki_data:
  grafana_data:
  prometheus_data:
