services:
  # Сервис
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bitrix-server-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  # Кеш
  redis:
    image: redis:latest
    container_name: bitrix-server-redis
    env_file:
      - ./.env
    ports:
      - "3001:6379"
    volumes:
      - /home/data/bitrix24/redisdata:/data
    networks:
      - monitoring
    command:
      - redis-server --appendonly yes
      - redis-server --requirepass  ${REDIS_PASSWORD}
    restart: always

  # Сбор логов
  alloy:
    image: grafana/alloy:latest
    container_name: bitrix-server-grafana_alloy
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - monitoring
    command:
      - run
      - /etc/alloy/config.alloy
    privileged: true

  # Хранение логов
  loki:
    image: grafana/loki:latest
    container_name: bitrix-server-grafana_loki
    ports:
      - "3002:3100"
    volumes:
      - loki_data:/loki
    networks:
      - monitoring
    command: -config.file=/etc/loki/local-config.yaml
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -tries=1 -O- http://localhost:3100/ready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Сбор метрик
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "3003:9090"
    volumes:
      - ./config/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    networks:
      - monitoring
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    depends_on:
      - backend

  # Дашборды
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3004:3000"
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring
    depends_on:
      - prometheus
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --tries=1 -O- http://localhost:3000/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  monitoring:
    driver: bridge

volumes:
  loki_data:
  grafana_data:
  prometheus_data:
