services:
  # Сервис
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bitrix-server-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  # Кеш
  redis:
    image: redis:latest
    container_name: bitrix-server-redis
    env_file:
      - .env
    ports:
      - "3001:6379"
    volumes:
      - /home/data/bitrix24/redisdata:/data
    command: redis-server --appendonly yes
    restart: always

  # Сбор логов
  alloy:
    image: grafana/alloy:latest
    container_name: bitrix-server-grafana_alloy
    volumes:
      - ./alloy-config.yaml:/etc/alloy/alloy-config.yaml
    command: [ "-config.file=/etc/alloy/alloy-config.yaml" ]
    depends_on:
      - loki

  # Хранение логов
  loki:
    image: grafana/loki:latest
    container_name: bitrix-server-grafana_loki
    ports:
      - "3002:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/loki-config.yaml

  # Сбор метрик
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "3003:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  # Дашборды
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3004:3000"
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki

volumes:
  grafana-data:
  prometheus-data:
  loki-data: