scrape_configs:
  - job_name: backend
    pipeline_stages:
      - docker: { }

      # Убираем ANSI
      - replace:
          expression: '\x1b\[[0-9;]*m'
          replace: ''

      # Только backend
      - match:
          selector: '{container_name="bitrix-server-backend"}'
          stages:
            - static_labels:
                service: nestjs
                env: production

            - regex:
                expression: '\[(?<level>DEBUG|ERROR|WARN|LOG|INFO)\]'

            - regex:
                expression: '\[(?<status>\d{3})\]\s(?<method>GET|POST|PUT|PATCH|DELETE)\s(?<path>\/\S*)\s-\s(?<user_agent>[^=]+)\s=>\s(?<duration_ms>\d+)ms'

            - labels:
                level:
                method:
                status:

    static_configs:
      - targets: [ localhost ]
        labels:
          job: docker-logs
          __path__: /var/lib/docker/containers/*/*-json.log

  # Другие контейнеры отдельно (Loki, Grafana)
  - job_name: docker-other
    pipeline_stages:
      - docker: { }
    static_configs:
      - targets: [ localhost ]
        labels:
          job: docker-other
          __path__: /var/lib/docker/containers/*/*-json.log
