global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'bitrix24_app'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'backend:3000' ]

remote_write:
  - url: 'http://mimir:3005/api/v1/push'