name: Deploy to Server

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    name: Update server by ssh
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/projects/bitrix24
            
            git fetch origin master
            
            LOCAL=$(git rev-parse HEAD)
            REMOTE=$(git rev-parse origin/master)
            
             if [ "$LOCAL" = "$REMOTE" ]; then
              echo "✅ Already up to date. Exit"
              exit 0
             fi
            git pull origin master
            docker compose build
            docker compose up -d --no-deps

      - name: Notify about error
        if: failure()
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d text="❌ Деплой в ветку ${{ github.ref }} завершился с ошибкой!\r\nКомит: ${{ github.event.head_commit.message }}"